(function(){
'use strict';
var PENDING='flowz_duo_pending';
function parse(v){try{return v?JSON.parse(v):null}catch(e){return null}}
function save(v){try{localStorage.setItem(PENDING,JSON.stringify(v))}catch(e){}}
function text(el,v){if(el&&el.textContent!==v)el.textContent=v}
function profile(){return document.body&&document.body.dataset.profile==='leni'?'leni':'kedy'}
function setMode(button,id,title,sub,icon){if(!button)return;if(id)button.id=id;text(button.querySelector('b'),title);text(button.querySelector('small'),sub);text(button.querySelector('.icon'),icon)}
function ensureLabel(box,id,value){var el=document.getElementById(id);if(!el){el=document.createElement('div');el.id=id}text(el,value);return el}
function ensureFree(box){var el=document.getElementById('flowzFreeTile');if(!el){el=document.createElement('button');el.type='button';el.id='flowzFreeTile';el.className='mode m4';el.innerHTML='<b>FREE</b><small>Open conversation · 10min</small><span class="icon">🎲</span>'}return el}
function styles(){if(document.getElementById('flowz439Modes'))return;var s=document.createElement('style');s.id='flowz439Modes';s.textContent='body[data-profile="kedy"] #modes{grid-template-columns:1fr 1fr}body[data-profile="kedy"] #modes .mode{display:block!important;min-height:84px}body[data-profile="kedy"] #modes .mode:first-child{display:none!important}body[data-profile="kedy"] #modes .mode small{display:block;max-width:82%;margin-top:7px;line-height:1.25}#flowzBathLabel,#flowzAnytimeLabel{grid-column:1/-1;margin:4px 2px 0;color:#9aa1aa;font-size:10px;font-weight:900;letter-spacing:.12em}#flowzReviewTile,#flowzFreeTile{grid-column:1/-1;min-height:70px}#flowzReviewTile{background:linear-gradient(145deg,#20c7cc,#16aeb8)!important;color:#012428!important}#flowzFreeTile{background:linear-gradient(145deg,#30363d,#20252b)!important;border:1px solid #4b555f!important;color:#f7f3e9!important}';document.head.appendChild(s)}
function layout(){if(profile()!=='kedy')return;var box=document.getElementById('modes');if(!box)return;var b=[].slice.call(box.children).filter(function(x){return x.classList&&x.classList.contains('mode')});if(b.length<4)return;var commute=b[0],toeic=b[1],study=b[2],review=document.getElementById('flowzReviewTile')||b[3],free=ensureFree(box);review.id='flowzReviewTile';setMode(toeic,'','TOEIC CHECK','Voice 5Q · L3/R2 · 5–8min','🎯🎤');setMode(study,'','TOEIC STUDY','Voice 5Q · 5–8min','🛁🎤');setMode(review,'flowzReviewTile','REVIEW','Recent phrases · 3–5min','🔁');setMode(free,'flowzFreeTile','FREE','Open conversation · 10min','🎲');var bath=ensureLabel(box,'flowzBathLabel','🛁 BATH ROUTINE · mikan 30 → Flowz'),any=ensureLabel(box,'flowzAnytimeLabel','🎲 ANYTIME · OPEN TALK');[commute,bath,toeic,study,review,any,free].forEach(function(x){box.appendChild(x)})}
function mission(kind,scroll){var panel=document.getElementById('mission');if(!panel)return;panel.classList.add('show');if(kind==='review'){text(document.getElementById('missionMode'),'REVIEW');text(document.getElementById('missionTheme'),'Recent phrase review');text(document.getElementById('missionPhrase'),'Use your recent English again.');text(document.getElementById('missionMeaning'),'直近の訂正フレーズを3つ復習');text(document.getElementById('missionGuide'),'3–5 minutes. One Japanese situation at a time.');text(document.getElementById('startBtn'),'START REVIEW')}else{text(document.getElementById('missionMode'),'FREE');text(document.getElementById('missionTheme'),'Open conversation');text(document.getElementById('missionPhrase'),'It depends on the situation.');text(document.getElementById('missionMeaning'),'状況による');text(document.getElementById('missionGuide'),'No fixed lesson. Talk about whatever is on your mind.');text(document.getElementById('startBtn'),'START FREE TALK')}if(scroll)panel.scrollIntoView({behavior:'smooth',block:'center'})}
function choose(kind){var p=kind==='review'?{profile:'kedy',mode:'review',title:'REVIEW',mission:{theme:'Recent phrase review',phrase:"It's cooler than usual.",meaning:'直近フレーズを復習'}}:{profile:'kedy',mode:'free',title:'FREE',mission:{theme:'Open conversation',phrase:'It depends on the situation.',meaning:'状況による'}};save(p);mission(kind,true)}
function prompt(kind,p){if(kind==='review')return ["You are kedy's English review coach in Flowz.","Run a short 3–5 minute review.","Use connected Notion only after the first natural reply to read recent Diary English Logs and choose three corrected or useful phrases.","Give one short Japanese situation at a time. Let kedy answer in English. Correct only important mistakes, allow one retry, then continue.","Do three items. At the end append a Review Log to today's existing Diary page and fetch it again to verify. Do not create a new Diary page."].join(' ');return ["You are kedy's practical English conversation partner in Flowz Duo Battle.","Start with a short natural reply and continue a real conversation.","Never end a turn with only praise, acknowledgement, or phrases such as Perfect, You're welcome, Got it, or Thanks. Continue with a natural question or topic.","Use short spoken English. Correct only meaning-changing or strongly unnatural mistakes.","Do not end unless kedy clearly ends the conversation. At wrap-up append a Free Talk English log to today's existing Diary page and verify it."].join(' ')}
window.addEventListener('click',function(e){if(profile()!=='kedy'||!e.target.closest)return;if(e.target.closest('#flowzReviewTile')){e.preventDefault();e.stopImmediatePropagation();choose('review');return}if(e.target.closest('#flowzFreeTile')){e.preventDefault();e.stopImmediatePropagation();choose('free');return}if(!e.target.closest('#startBtn'))return;var p=parse(localStorage.getItem(PENDING));if(!p||p.startedAt||(p.mode!=='review'&&p.mode!=='free'))return;e.preventDefault();e.stopImmediatePropagation();p.startedAt=new Date().toISOString();p.autoRecord=true;save(p);var q=prompt(p.mode,p);try{navigator.clipboard.writeText(q)}catch(err){}location.href='https://chatgpt.com/?q='+encodeURIComponent(q)},true);
function apply(){styles();layout();var p=parse(localStorage.getItem(PENDING));if(p&&p.profile==='kedy'&&(p.mode==='review'||p.mode==='free'))mission(p.mode,false)}
document.addEventListener('DOMContentLoaded',function(){apply();setTimeout(apply,500)});window.addEventListener('pageshow',function(){setTimeout(apply,30)});document.addEventListener('click',function(e){if(e.target.closest&&e.target.closest('.profile-btn'))setTimeout(apply,30)});
})();
